/**
 * Local HTTPS dev server for the Word Data Merger add-in.
 * Serves the project root on https://localhost:3000
 *
 * Usage: node server.js
 *
 * Certs are generated by office-addin-dev-certs (run `npm run install-certs` first).
 */

const https = require("https");
const fs    = require("fs");
const path  = require("path");

const PORT      = 3000;
const ROOT      = __dirname;
const CERT_DIR  = path.join(require("os").homedir(), ".office-addin-dev-certs");

const MIME = {
  ".html": "text/html",
  ".css":  "text/css",
  ".js":   "application/javascript",
  ".json": "application/json",
  ".png":  "image/png",
  ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
};

function certPath(name) {
  return path.join(CERT_DIR, name);
}

function startServer(opts) {
  const server = https.createServer(opts, (req, res) => {
    let urlPath = req.url.split("?")[0];
    if (urlPath === "/") urlPath = "/src/taskpane/taskpane.html";

    const filePath = path.join(ROOT, urlPath);

    // Prevent path traversal
    if (!filePath.startsWith(ROOT)) {
      res.writeHead(403);
      res.end("Forbidden");
      return;
    }

    fs.readFile(filePath, (err, data) => {
      if (err) {
        res.writeHead(404, { "Content-Type": "text/plain" });
        res.end("Not found: " + urlPath);
        return;
      }
      const ext  = path.extname(filePath);
      const mime = MIME[ext] || "application/octet-stream";
      res.writeHead(200, {
        "Content-Type": mime,
        "Access-Control-Allow-Origin": "*",
      });
      res.end(data);
    });
  });

  server.listen(PORT, () => {
    console.log(`Word Data Merger server running at https://localhost:${PORT}`);
    console.log(`Task pane: https://localhost:${PORT}/src/taskpane/taskpane.html`);
    console.log("Press Ctrl+C to stop.");
  });
}

// Try to load office-addin-dev-certs certs
const keyFile  = certPath("localhost.key");
const certFile = certPath("localhost.crt");
const caFile   = certPath("ca.crt");

if (fs.existsSync(keyFile) && fs.existsSync(certFile)) {
  const opts = {
    key:  fs.readFileSync(keyFile),
    cert: fs.readFileSync(certFile),
  };
  if (fs.existsSync(caFile)) opts.ca = fs.readFileSync(caFile);
  startServer(opts);
} else {
  console.error(
    "Dev certs not found. Run:\n  npx office-addin-dev-certs install\nthen try again."
  );
  process.exit(1);
}
